sudo: required  
dist: trusty  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '6.1'
cache:
  directories:
  - node_modules
before_install:  
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
- java -jar selenium-server-standalone-2.44.0.jar &> /dev/null &
install:
- travis_retry npm install -g grunt-cli
- travis_retry npm install
before_script:
  - sleep 5
  - npm install -g bower
  - bower install
script:
- grunt
- node_modules/.bin/intern-runner config=tests/intern
